### ISSUE TITLE
How to migrate from ELB to NLB ?

### ISSUE THREAD

**Issue by scheung38** [andreivmaksimov/terraform-recipe-managing-auto-scaling-groups-and-load-balancers#1]
Could you show how to thanks

**Comment by andreivmaksimov** [comment]
You need to use 
```
resource "aws_lb" 
```
with
``` 
load_balancer_type = "network"
```

**Comment by scheung38** [comment]
Any idea why ports say 8883 with ingress  are defined in security group in the same manner as ssh port 22, but upon ssh into EC2 instance

Netstat - tunlp

Only sees 22

**Comment by andreivmaksimov** [comment]
@scheung38, answered in a [separate](https://github.com/andreivmaksimov/terraform-recipe-managing-auto-scaling-groups-and-load-balancers/issues/3) ticket
